-- =====================================================
-- INSERT para tabla parametro_hijo con parametro_id = 4 (Cargos)
-- Generado automaticamente desde cargos.txt
-- Base de datos: MySQL
-- Total de cargos: 74
-- =====================================================

-- Configuracion inicial para MySQL
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Limpiar datos existentes (opcional)
-- DELETE FROM parametro_hijo WHERE parametro_id = 4;

-- Lote 1 de 2 (registros 1-50)
INSERT INTO parametro_hijo (parametro_id, nombre, descripcion, estado) VALUES
(4, 'ABOGADA', 'CARGO DEL EMPLEADO', 1),
(4, 'ANESTESIOLOGO', 'CARGO DEL EMPLEADO', 1),
(4, 'APRENDIZ - UNIVERSITARIO', 'CARGO DEL EMPLEADO', 1),
(4, 'APRENDIZ SENA', 'CARGO DEL EMPLEADO', 1),
(4, 'APRENDIZ SENA - ETAPA LECTIVA', 'CARGO DEL EMPLEADO', 1),
(4, 'ASISTENTE CONTABLE', 'CARGO DEL EMPLEADO', 1),
(4, 'ASISTENTE DE AMBIENTE SEGURO', 'CARGO DEL EMPLEADO', 1),
(4, 'ASISTENTE DE GERENCIA Y TESORERIA', 'CARGO DEL EMPLEADO', 1),
(4, 'ASISTENTE DE GESTION DE CARTERA Y GLOSAS', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR ADMINISTRATIVA CANGURO', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR CONTABLE 1', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE ADMISIONES Y ASIGNACION DE CITAS', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE ADMISIONES Y AUTORIZACIONES', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE ENFERMERIA', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE FACTURACIÓN', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE FARMACIA', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE GESTIÓN DOCUMENTAL', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE INFORMACIÓN EN SALUD', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE LABORATORIO CLÍNICO', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE PERSONAL', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE RADICACIÓN', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE REFERENCIA, CONTRAREFERENCIA Y ATENCION PRIORITARIA', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR DE SISTEMAS 1', 'CARGO DEL EMPLEADO', 1),
(4, 'AUXILIAR SERVICIOS AMBULATORIOS', 'CARGO DEL EMPLEADO', 1),
(4, 'BACTERIOLOGO', 'CARGO DEL EMPLEADO', 1),
(4, 'CAMILLERO', 'CARGO DEL EMPLEADO', 1),
(4, 'CIRUJANO PEDIÁTRICO', 'CARGO DEL EMPLEADO', 1),
(4, 'CONTADOR JUNIOR', 'CARGO DEL EMPLEADO', 1),
(4, 'COORDINADORA BIOMEDICA E INFRAESTRUCTURA Y PRODUCCION DE AIRE MEDICINAL', 'CARGO DEL EMPLEADO', 1),
(4, 'COORDINADORA DE GESTION DE CARTERA Y GLOSAS', 'CARGO DEL EMPLEADO', 1),
(4, 'COORDINADORA DE PLANEACION Y CALIDAD', 'CARGO DEL EMPLEADO', 1),
(4, 'COORDINADORA DE SISTEMAS DE INFORMACIÓN Y COMUNICACIONES', 'CARGO DEL EMPLEADO', 1),
(4, 'COORDINADORA DE TALENTO HUMANO', 'CARGO DEL EMPLEADO', 1),
(4, 'COORDINDORA DE FACTURACIÓN', 'CARGO DEL EMPLEADO', 1),
(4, 'DIRECTOR TÉCNICO DEL SERVICIO FARMACEUTICO', 'CARGO DEL EMPLEADO', 1),
(4, 'ENDOCRINÓLOGO PEDIÁTRA', 'CARGO DEL EMPLEADO', 1),
(4, 'ENFERMERA PROFESIONAL ESPECIALIZADA', 'CARGO DEL EMPLEADO', 1),
(4, 'ENFERMERO PROFESIONAL', 'CARGO DEL EMPLEADO', 1),
(4, 'ENFERMERO(A) PROFESIONAL', 'CARGO DEL EMPLEADO', 1),
(4, 'FISIOTERAPEUTA', 'CARGO DEL EMPLEADO', 1),
(4, 'FONOAUDIOLOGA', 'CARGO DEL EMPLEADO', 1),
(4, 'GENETISTA', 'CARGO DEL EMPLEADO', 1),
(4, 'GERENTE GENERAL', 'CARGO DEL EMPLEADO', 1),
(4, 'GINECÓLOGO (A)', 'CARGO DEL EMPLEADO', 1),
(4, 'GINECOLOGO Y OBSTETRA', 'CARGO DEL EMPLEADO', 1),
(4, 'INSTRUMENTADOR (A) QUIRÚRGICA', 'CARGO DEL EMPLEADO', 1),
(4, 'JEFE DEL DEPARTAMENTO DE ENFERMERIA', 'CARGO DEL EMPLEADO', 1),
(4, 'LIDER CENTRAL DE CITAS 13/06/2024', 'CARGO DEL EMPLEADO', 1),
(4, 'LIDER DE MATERNIDAD SEGURA Y MORTALIDAD', 'CARGO DEL EMPLEADO', 1),
(4, 'LIDER DE SEGURIDAD DEL  PACIENTE', 'CARGO DEL EMPLEADO', 1);

-- Lote 2 de 2 (registros 51-74)
INSERT INTO parametro_hijo (parametro_id, nombre, descripcion, estado) VALUES
(4, 'LIDER DE SIVIGILA, COVED, PROA Y APOYO COMITÉ DE INFECCIONES', 'CARGO DEL EMPLEADO', 1),
(4, 'MEDICO AUDITOR CONCURRENTE DE CUENTAS MEDICAS', 'CARGO DEL EMPLEADO', 1),
(4, 'MEDICO GENERAL', 'CARGO DEL EMPLEADO', 1),
(4, 'MÉDICO PEDIATRA', 'CARGO DEL EMPLEADO', 1),
(4, 'MÉDICO PEDIATRA-NEONATÓLOGO', 'CARGO DEL EMPLEADO', 1),
(4, 'MENSAJERO', 'CARGO DEL EMPLEADO', 1),
(4, 'NUTRICIONISTA DIETISTA', 'CARGO DEL EMPLEADO', 1),
(4, 'PROFESIONAL EN SEGURIDAD Y SALUD EN EL TRABAJO', 'CARGO DEL EMPLEADO', 1),
(4, 'PSICÓLOGO (A)', 'CARGO DEL EMPLEADO', 1),
(4, 'RECEPCIONISTA/CAJERA', 'CARGO DEL EMPLEADO', 1),
(4, 'REGENTE DE FARMACIA', 'CARGO DEL EMPLEADO', 1),
(4, 'SECRETARIA', 'CARGO DEL EMPLEADO', 1),
(4, 'SUBGERENTE ADMINISTRATIVA Y FINANCIERA', 'CARGO DEL EMPLEADO', 1),
(4, 'SUBGERENTE ASISTENCIAL', 'CARGO DEL EMPLEADO', 1),
(4, 'TÉCNICO EN INFORMACIÓN EN SALUD', 'CARGO DEL EMPLEADO', 1),
(4, 'TÉCNICO EN MANTENIMIENTO E INFRAESTRUCTURA', 'CARGO DEL EMPLEADO', 1),
(4, 'TÉCNICO EN SISTEMAS', 'CARGO DEL EMPLEADO', 1),
(4, 'TECNÓLOGO EN IMÁGENES DIAGNOSTICAS', 'CARGO DEL EMPLEADO', 1),
(4, 'TERAPEUTA OCUPACIONAL', 'CARGO DEL EMPLEADO', 1),
(4, 'TERAPEUTA RESPIRATORIO', 'CARGO DEL EMPLEADO', 1),
(4, 'TRABAJADOR SOCIAL- SIAU', 'CARGO DEL EMPLEADO', 1),
(4, 'TRANSCRIPTORA', 'CARGO DEL EMPLEADO', 1),
(4, 'TRANSCRIPTORA Y AUXILIAR ADMVA RAYOS X', 'CARGO DEL EMPLEADO', 1),
(4, 'TRANSCRIPTORA Y AUXILIAR ADTVA RAYOS X', 'CARGO DEL EMPLEADO', 1);

-- Restaurar configuracion
SET FOREIGN_KEY_CHECKS = 1;

-- Verificar insercion
SELECT COUNT(*) as total_cargos FROM parametro_hijo WHERE parametro_id = 4;

-- Mostrar algunos ejemplos
SELECT id_parametrohijo, nombre, descripcion FROM parametro_hijo WHERE parametro_id = 4 LIMIT 10;